spring:
  datasource:
    name: jk-fast-start
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update