spring:
  datasource:
    name: jk-fast-start
    url: jdbc:mysql://192.168.1.156:3306/test?useUnicode=true
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
  jpa:
    show-sql: true